### ISSUE TITLE
add ability to supply JSON or XML text so no need to convert to list

### ISSUE THREAD

**Issue by timelyportfolio** [timelyportfolio/listviewer#1]
JSON string easy to add.

For XML, will need to convert to JSON.
- https://github.com/metatribal/xmlToJSON
- https://developer.mozilla.org/en-US/docs/JXON

**Comment by cpsievert** [comment]
There's also this (haven't actually used it)

https://github.com/johndharrison/JSON2XML

(As well as `XML::xmlToList()`)

**Comment by jennybc** [comment]
The example I sent was made with `XML::xmlToList()`.

**Comment by timelyportfolio** [comment]
is this safe to close?
