### ISSUE TITLE
doesn't like named vector

### ISSUE THREAD

**Issue by stanstrup** [timelyportfolio/listviewer#10]
This package is a great. It does't seem to like named vectors though. I am flooded with this:

```
Input to asJSON(keep_vec_names=TRUE) is a named vector. In a future version of jsonlite, this option will not be supported, and named vectors will be translated into arrays instead of objects. If you want JSON object output, please use a named list instead. See ?toJSON.
```

Perhaps it can convert first to lists to avoid this?

**Comment by timelyportfolio** [comment]
good point.  let me think about this.  I like for users to be warned, but I understand it can be annoying.  I imagine most `listviewer` users are not that concerned with the subtlety.

**Comment by timelyportfolio** [comment]
My first line of thought is to convert as you suggest, but could potentially be more problematic than the annoying warning.  I'm thinking something like

```
if( !inherits(listdata,"list") && is.null(dim(listdata)) && !is.null(names(listdata)) ){
  listdata <- as.list(listdata)
}
```

**Comment by timelyportfolio** [comment]
Thinking through this more, since I am not recursively applying throughout a list, the warning will still appear in the case of a named `vector` nested in a `list` or `data.frame`.  I guess that is ok as long as we are aware.

**Comment by timelyportfolio** [comment]
Another "solution" would be to simply create a custom `toJSON` that wraps the standard `toJSON` or `toJSON2` with `suppressWarnings` but that could also introduce problems.

**Comment by timelyportfolio** [comment]
@stanstrup I am going to close this, since 9a866b7 will now automatically convert a named `vector` into a `list`.  Thanks so much for using and reporting.  Let me know if I experience any other troubles or pains.

**Comment by stanstrup** [comment]
Thanks for the fast response! What about doing it recursively? I tried to pre-treat my list and it didn't seem to have bad effects.

```
names_vec2list <- function(listdata){
  if(
    !inherits(listdata,"list") &&
    is.null(dim(listdata)) &&
    !is.null(names(listdata))
  ){
    listdata <- as.list(listdata)
  }
  return(listdata)
}


listdata<- rapply(listdata,names_vec2list,how="list")
```

**Comment by timelyportfolio** [comment]
@stanstrup, just didn't do this out of fear.  Guess I might as well go all the way.

**Comment by timelyportfolio** [comment]
@stanstrup, done; let me know how it looks

**Comment by stanstrup** [comment]
Beautiful! Thanks!

**Comment by timelyportfolio** [comment]
@stanstrup, I should have noted I chose to only recursively convert `list` to avoid complications with `data.frame` and `tbl_df`.  Thanks again for the issue.
