### ISSUE TITLE
How to access list contents from shiny

### ISSUE THREAD

**Issue by scizmeli** [timelyportfolio/listviewer#15]
Hi there

It's wonderful tool. Very useful. Thank you.

I was able to successfully display the contents of a list with jsonedit() in a shiny app. Now when I change the displayed values, I would like to be able to have the changed value saved back into the original copy of the list variable in the memory. 

Normally,  I would build a reactive block that executes every time a value of the list shown by jsonedit() is changed by the user.  But I can't figure out how to achieve this with jsonedit()

Can you please help?

**Comment by timelyportfolio** [comment]
This is a little tricky, since event handling with `jsoneditor` isn't super easy (see https://github.com/josdejong/jsoneditor/issues/39).  We do get `onChange` though. Please note the entire data is sent, not just a patch, so be careful with big data.

```
library(listviewer)
library(shiny)

shinyApp(
  ui = jsoneditOutput("jsonedit1"),
  server = function(input,output,session){
    output$jsonedit1 <- renderJsonedit({
      
      jsonedit(
        mtcars,
        onChange=htmlwidgets::JS(
"
function(){
  Shiny.onInputChange(
    'jsonedit1_change',
    HTMLWidgets.getInstance(document.getElementById('jsonedit1')).editor.getText()
  );
}
"
        )
      )
    })
    
    observeEvent(input$jsonedit1_change,{
      print(input$jsonedit1_change)
    })
  }
)
```

**Comment by scizmeli** [comment]
This totally works. Wonderful. For now I only manage app settings, so size is not a big issue. 
thanks
