### ISSUE TITLE
Hide header/border?

### ISSUE THREAD

**Issue by mbacou** [timelyportfolio/listviewer#17]
Just wondering if I can pass a few options to hide the widget header (top bar) and border (I am embedding this widget into RMarkdown documents, trying to keep it simple). Very useful overall!

**Comment by timelyportfolio** [comment]
Yes, this is possible. I like the idea, and I will add an example in just a bit.

**Comment by timelyportfolio** [comment]
@mbacou, here is a quick example, and at the end I wrap it into a convenience function.

```
library(listviewer)

je <- jsonedit(par())

# using the technique proposed here
#   for custom htmlwidget styling
#   https://github.com/ramnathv/htmlwidgets/issues/231
#   darn, I forgot to add elementId as argument
#   and will fix in future version

# for now manually add elementId
elid <- sprintf(
  "jsonedit-%s",
  htmlwidgets:::createWidgetId()
)
# add the elementId to our jsonedit
#  this will be much easier in future
je$elementId <- elid

# use prependContent for custom styling
htmlwidgets::prependContent(
  je,
  htmltools::tags$style(
sprintf(
  "
#%s .jsoneditor-menu {
  display: none;
}
#%s .jsoneditor {
  border: none;
}
  ",
  elid,
  elid
)    
  )
)
```

![image](https://cloud.githubusercontent.com/assets/837910/19602418/cc0f8cdc-9772-11e6-822b-864da0e5c3dc.png)


### as a function

```
# make it a function for easy reuse
je_simple_style <- function(je){
  # for now manually add elementId
  elid <- sprintf(
    "jsonedit-%s",
    htmlwidgets:::createWidgetId()
  )
  # add the elementId to our jsonedit
  #  this will be much easier in future
  je$elementId <- elid
  
  # use prependContent for custom styling
  htmlwidgets::prependContent(
    je,
    htmltools::tags$style(
sprintf(
"
#%s .jsoneditor-menu {
  display: none;
}
#%s .jsoneditor {
  border: none;
}
",
elid,
elid
      )    
    )
  )
}

# use our function
je_simple_style(
  jsonedit(mtcars)
)
```

**Comment by mbacou** [comment]
Perfect! You're planning to merge this feature into the master branch, right?

**Comment by mbacou** [comment]
`je_simple_style()` does not seem to work in a Shiny app for some reason -- but not a big problem.

**Comment by timelyportfolio** [comment]
@mbacou, this is expected, since `id` in Shiny works a little differently.  I am glad you mentioned it, since I should have discussed this use case in the earlier answer.  Shiny assigns the `id` based on the `id` argument of the `*Output` function.  Here is one way to do in Shiny.

*however, I just noticed that the styling is not specific enough and we lose context menus*

```
# use in Shiny
library(shiny)
library(listviewer)

elid <- "myjsonedit"

custom_sty <- htmltools::tags$style(
  sprintf(
    "
    #%s .jsoneditor-menu {
    display: none;
    }
    #%s .jsoneditor {
    border: none;
    }
    ",
    elid,
    elid
  )    
)

ui <- tagList(
  custom_sty,
  jsoneditOutput(outputId=elid)
)
  

server <- function(input, output, session) {
  output$myjsonedit <- renderJsonedit({
    jsonedit(mtcars)
  })
}

shinyApp(ui, server)
```

**Comment by timelyportfolio** [comment]
@mbacou, I amended the above answers to only disable the header menu and not the context menus.  I think you will like this better.

**Comment by mbacou** [comment]
Thanks for the quick fix
