### ISSUE TITLE
Index from 1

### ISSUE THREAD

**Issue by jennybc** [timelyportfolio/listviewer#18]
When using `jsonedit()` on an unnamed list, elements are labelled by index. Could these indices start at 1 for easier translation between the interactive view and the composition of `[`, `[[`, and `map(my_list, INTEGER)` commands?

<img width="229" alt="screen shot 2016-10-24 at 10 41 55 pm" src="https://cloud.githubusercontent.com/assets/599454/19674200/424907dc-9a3b-11e6-976f-7b4d8be01618.png">

**Comment by timelyportfolio** [comment]
I fear this one might be messy and require changes to the underlying `jsoneditor`.  I generally try to avoid changes to the underlying library especially in the case of something as great, big, and complicated as `jsoneditor`.  I will poke around to see what I find.

**Comment by timelyportfolio** [comment]
... unless on the `R` side we name `unname`d lists/arrays starting with `1

**Comment by timelyportfolio** [comment]
@jennybc, as discussed above in https://github.com/timelyportfolio/listviewer/issues/18#issuecomment-257339297, here is how we might handle on the `R` side.

```
recurse <- function(l, func, ...) {
  l <- func(l, ...)
  if(is.list(l) && length(l)>0){
    lapply(
      l,
      function(ll){
        recurse(ll, func, ...)
      }
    )
  } else {
    l
  }
}

add_number_names <- function(l){
  if(length(l)>0 && is.null(names(l))){
    names(l) <- seq_len(length(l))
  }
  l
}

listviewer::jsonedit(recurse(list(1:3), add_number_names))
```

**Comment by timelyportfolio** [comment]
If we did this, I would think this should be optional behind an argument, since translation back to `R` will cause problems.

**Comment by jennybc** [comment]
Yes that would be great. Definitely agree re: optional. Naming the actual list currently has other unfortunate consequences for how, e.g., purrr operates. This is why I leave so many lists unnamed, when otherwise I would pull a name out of the list itself. But better labelling in the widget would be helpful.

**Comment by timelyportfolio** [comment]
Personally, I try to minimize arguments to a `function`.  Would adding a documented and exported helper function be acceptable, or would you prefer it be a an argument?

**Comment by jennybc** [comment]
I'd be happy to run the input through a helper first. I don't really expose the listviewer code in the tutorial anyway.

**Comment by jennybc** [comment]
While we're discussing interface, I've thought that the name `jsonedit()` is a bit misleading. Why? First, I'm working with a list. Which may or may not have come from JSON. Second, I have no immediate plans to edit my list in this way and I'm not even sure I'd be on board with that, for the same reason I won't edit data by hand in Excel. Maybe the JS library you're wrapping sort of dictates the name? If not, I humbly submit `listview()` as an option worth considering.

**Comment by timelyportfolio** [comment]
I really like the idea of `listview`.  Originally, I had intended to provide a separate function for each viewer and then have a wrapper function like `listview`.  We did something similar in `DiagrammeR` with mermaid and viz.js.  `jsoneditor` is so amazing that I might just dedicate `listviewer` to it.  Tough decisions :)

**Comment by timelyportfolio** [comment]
I have added a `number_unnamed` helper function.  Once I hear feedback, I will push the submit to CRAN button.  Thanks again.

**Comment by jennybc** [comment]
I've tried `number_unnamed()`. The R-like indexing from one is great. But something else has changed that is less desirable. Not sure if same root cause?

Here's before, I which we can see the sub-component names and values?

<img width="667" alt="screen shot 2016-11-01 at 7 36 47 am" src="https://cloud.githubusercontent.com/assets/599454/19893375/34098748-a006-11e6-8ab4-f5e5af9654d4.png">

Here's after:
<img width="670" alt="screen shot 2016-11-01 at 7 37 05 am" src="https://cloud.githubusercontent.com/assets/599454/19893393/4290547c-a006-11e6-8d59-3cf695b1d02d.png">

See how all the sub-components are de-expanded now and I would need to click on each one to reveal its single unit of info?

Is it possible to have the indexing from 1 and not this other behaviour?

**Comment by jennybc** [comment]
This does seem to have something to do with running the primary input list through `number_unnamed()`. If I revert (and tolerate the display of 0-based indices), the sub-components display compactly again.

**Comment by timelyportfolio** [comment]
Makes sense, I had set the check to `length(l)>0` which will assign numbers to unnamed single element list/vector.  I just changed the check to `length(l) > 1` which will mean we don't get a name on single element list/vector.  Will you please verify on your end?  Thanks!

Here is my test case.

```
l <- list(
  list(
    a="a",
    b="b"
  ),
  list(
    a="a",
    b="b"
  )
)

jsonedit(l)

jsonedit(number_unnamed(l))
```

![image](https://cloud.githubusercontent.com/assets/837910/19894981/fbeb7512-a01c-11e6-931b-9deafe8fc9cb.png)

**Comment by timelyportfolio** [comment]
going to close this; please let me know if it should be reopened.
