### ISSUE TITLE
Don't generate random id

### ISSUE THREAD

**Issue by jennybc** [timelyportfolio/listviewer#19]
I'm not sure if this is a listviewer problem or an htmlwidget problem.

I'm using listviewer in an R markdown website and every time I build the site, the listviewer widgets have a diff, even thought the data does not change. I made a commit consisting solely of this phenomenon as an example:

https://github.com/jennybc/purrr-tutorial/commit/010cb570000a5e023c0a1d371dbd25e6f128dc8d

Is there any way to suppress that?

**Comment by timelyportfolio** [comment]
This is not unique to `listviewer`, but there is an easy solution for all `htmlwidgets` that I failed to provide for `listviewer`.  All `htmlwidgets` will get a pseudo-random id unless they specify the `elementId` in `createWidget`.  I just added to `jsonedit`, and I will try to get up to CRAN by end of the week.

```
# devtools::install_github("timelyportfolio/listviewer")
library(listviewer)
jsonedit(list(), elementId="my-special-unique-id")
```

![image](https://cloud.githubusercontent.com/assets/837910/19855909/f1c585ba-9f44-11e6-8141-7d6477871506.png)

### other htmlwidgets

For other `htmlwidgets`, proper usage and implementation of `elementId` varies by author and timing.  However after creation, you can add an `elementId` for other `htmlwidgets` by assigning an `elementId` after construction.  Assuming I did not add the `elementId` argument to `jsonedit`, here is how we could achieve this.

```
# see above for better usage but here is a way to provide elementId
#    if a htmlwidget does not provide a elementId argument in the constructor function

library(listviewer)

je <- jsonedit(list())
je$elementId <- "my-special-override-id"
je
```

**Comment by jennybc** [comment]
I was also thinking maybe I could cache that chunk? Obviously I should just try that and see what happens. But I will look forward to using `elementId`. Thanks!

**Comment by timelyportfolio** [comment]
Sure, thanks for using and reporting!  I also added [`react-json`](https://github.com/arqex/react-json) as another list viewer.  It is a much sparser react-based viewer.  There are a couple other really nice `react`-based json inspectors that I also plan to add soon.

Hopefully, I can submit this to CRAN by end of day.

**Comment by jennybc** [comment]
> Hopefully, I can submit this to CRAN by end of day.

Is there anyway a solution for this makes it in? #18

**Comment by jennybc** [comment]
I am using `elementId` as intended now. Does just what I hoped. Thanks.

**Comment by timelyportfolio** [comment]
Great, thanks for the reminder.  I was in such a rush last year with the widgets that I was not able to implement my checklist on them.  Really glad you are using `listviewer`.
