### ISSUE TITLE
Json display failed by jsonedit()

### ISSUE THREAD

**Issue by Hz-EMW** [timelyportfolio/listviewer#22]
Dear Maintainer and Authors:
I am so sorry to bordering you on the error of listviewer. During solving the problem of separate content of nonstandard table in the web page, I meet listviewer and found that it is a great visualization tool for list-like objects in R and Json.  
However, the jsonedit() function for Json runs without any results, the result page is blank. The example I run is in the listviewer document like below, and other example of jsonedit() runs well:
jsonedit(
'{"array" : [1,2,3] , "boolean" : true, "null" : null, number = 123}'
)
My working environment is Windows 7 Chinese Simplified Operating System, Internet Explorer 11, R 3.3.3 and latest packages.
I wonder if you could give me some advice on show Json with ‘listviewer’. Looking forward to hearing from you. Thank you very much.
                                     Sincerely yours 
                                     Humphrey Zhao

**Comment by timelyportfolio** [comment]
No problem at all.  The example `json` you provided is invalid.

![image](https://cloud.githubusercontent.com/assets/837910/25071083/1ef51bec-2274-11e7-9af7-b7dc2f386a51.png)

When corrected to valid `json` by adding quotes around `number` and changing `=` to `:`, the example works.

```
jsonedit(
    '{"array" : [1,2,3] , "boolean" : true, "null" : null, "number" : 123}'
)
```

Please let me know if this does not work for you.

**Comment by timelyportfolio** [comment]
feel free to reopen, but I believe this is solved
