### ISSUE TITLE
feature request : render html output

### ISSUE THREAD

**Issue by randomgambit** [timelyportfolio/listviewer#23]
Hello,

Another interesting idea. I would be nice if listviewer could render any html output stored into a dataframe.

For instance, most people who work with news datasets end up working with dataframes that contain the body of an article in html form (<html><body>\\n<div id=\"bb-style\">\\n\\n etc). 

Understanding what's going on is super tedious. Could `listviewer` process that and show the text in a more efficient way?

**Comment by timelyportfolio** [comment]
So something like convert html to JSON and then view in listviewer?  There is [himalaya.js](https://github.com/andrejewski/himalaya) that does this and a couple of others.

Thanks again for the ideas!

**Comment by randomgambit** [comment]
@timelyportfolio but can we do that in R?

**Comment by timelyportfolio** [comment]
Yes, definitely, and I am glad you asked, since both `XML` and `xml2` convert to lists.  This would be far easier, and if it works allow us to stay in the R ecosystem for this.  Here is a quick example.


```
library(xml2)
library(jsonlite)
library(listviewer)

# assumes html is directly available
#   read html from the original post about listviewer
post <- read_html("http://timelyportfolio.github.io/buildingwidgets/week15/")

# quick view of structure
html_structure(post)

# show it with listviewer
#  note, this shows everything and would probably want
#  to exclude head, script, etc.
jsonedit(
  toJSON(as_list(post), auto_unbox=TRUE)
)
```

**Comment by randomgambit** [comment]
@timelyportfolio very interesting! I tried your solution but it failed unfortunately...

in my dataframe, `Body` contains the body of an article in html format.

df_news %>% head(10) %>% select(Body) %>% listviewer::jsonedit(toJSON(as_list(read_html(.)), auto_unbox=TRUE))

gives

>  Error in UseMethod("read_xml") : 
>   no applicable method for 'read_xml' applied to an object of class "c('tbl_df', 'tbl', 'data.frame')
>

**Comment by randomgambit** [comment]
@timelyportfolio OK I was able to work on a single html element but your code still does not render  anything in the viewer:

The html looks like

` "<html xmlns=\"http://www.w3.org/1999/xhtml\"\\n      xmlns:xn=\"http://www.xmlnews.org/ns/\">\\n\\n<head>\\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\\n<title>Timelyportfolio is a great coder`

and piping it using 
```
 %>% read_html(.) %>% jsonedit(
  toJSON(as_list(.), auto_unbox=TRUE)
)

```
does not work.
any ideas? Thanks!!

**Comment by timelyportfolio** [comment]
Does something like this work for you?

```

library(xml2)
library(jsonlite)
library(listviewer)
library(dplyr)

div <- "<div>hi <p>olaf</p></div>"

data_frame(
  n = 1:10,
  divs = div
) %>%
  mutate(
    divs = lapply(divs, function(d){
      as_list(read_html(d))
    })
  ) %>%
  jsonlite::toJSON(auto_unbox=TRUE) %>%
  jsonedit()

```

**Comment by timelyportfolio** [comment]
I think this is solved, but @randomgambit feel free to reopen if we should continue the discussion.
