### ISSUE TITLE
Error in gsub("</", "\\u003c/", payload, fixed = TRUE) :    input string 1 is invalid UTF-8

### ISSUE THREAD

**Issue by randomgambit** [timelyportfolio/listviewer#24]
Hello,

I am getting this error while using `listviewer` on some url internet addresses. A simple `head()` on this data works, while `head() %>% listviewer:jsonedit()` gives the above error. 

Is this expected?
Thanks!

**Comment by timelyportfolio** [comment]
@randomgambit, would it be possible to provide a reproducible example?  This is very strange, but my first guess would be `json` conversion issue or an encoding problem.  Sorry, I took so long to respond.  I somehow missed this issue.

**Comment by timelyportfolio** [comment]
closing due to lack of response.  If you would like to provide some representative data, then I'd love to reopen and figure this out.
