### ISSUE TITLE
How to use Listviewer in R shiny

### ISSUE THREAD

**Issue by varu2794** [timelyportfolio/listviewer#26]
I am trying to use listviewer in shiny app .Can anyone help me render listviewer in  R shiny

**Comment by timelyportfolio** [comment]
As of now, we can get Shiny and `listviewer` to work together.  Here is an example from the Readme.

```
library(shiny)
library(listviewer)

# put some data in environment so it will show up
data(mtcars)

ui <- shinyUI(
  fluidPage(
    jsoneditOutput( "jsed" )
  )
)

server <- function(input,output){
  output$jsed <- renderJsonedit({
    jsonedit(
      as.list( .GlobalEnv )
      ,"change" = htmlwidgets::JS('function(){
        console.log( event.currentTarget.parentNode.editor.get() )
      }')
    )
    
  })
}

runApp( list( ui = ui, server = server ) )
```

In addition, the gadget code https://github.com/timelyportfolio/listviewer/blob/master/R/jsonedit_gadget.R might illustrate a slightly different way of Shiny + `listviewer` communication.

Please let me know if these don't work work for you.

**Comment by varu2794** [comment]
Its giving an error as (cannot coerce type 'environment' to vector of type 'list')

**Comment by timelyportfolio** [comment]
@varu2794, do you have a reproducible example?

**Comment by timelyportfolio** [comment]
closing due to lack of response.  If you'd like to reopen with a reproducible example, happy to attempt to help.  Thanks!
