### ISSUE TITLE
Pass R objects to reactjson props

### ISSUE THREAD

**Issue by cpsievert** [timelyportfolio/listviewer#27]
Loving the look and feel of `reactjson()`. Would love a way to leverage the react props https://github.com/mac-s-g/react-json-view#props

**Comment by timelyportfolio** [comment]
@cpsievert very delayed, but the newest release (off to CRAN a couple of minutes ago) should support nearly all `react-json-view` props.  Here is an example.

```
library(listviewer)

reactjson(
  list(
    array = c(1,2,3)
    ,boolean = TRUE
    ,null = NULL
    ,number = 123
    ,object = list( a="b", c="d" )
    ,string = "Hello World"
  ),
  theme = "monokai",
  iconStyle = "triangle",
  indentWidth = 10,
  sortKeys = TRUE,
  collapsed = 1
)
```

![image](https://user-images.githubusercontent.com/837910/46577774-d2eee280-c9b3-11e8-9519-db0e22d780f5.png)

**Comment by timelyportfolio** [comment]
going to close, but feel free to reopen if I missed anything or misinterpreted.
