### ISSUE TITLE
lapply options list

### ISSUE THREAD

**Issue by femiguez** [timelyportfolio/listviewer#35]
Example error:

> library(listviewer)
> library(xml2)
> xml1 <- read_html(system.file("extdata", "r-project.html", package = "xml2"))
> 
> xml2 <- as_list(xml1)
> jsonedit(xml2)
Error in FUN(X[[i]], ...) : 
  'options' must be a fully named list, or have no names (NULL)

traceback shows an error in a use of lapply

> traceback()
27: stop("'options' must be a fully named list, or have no names (NULL)")
26: FUN(X[[i]], ...)
25: lapply(options, shouldEval)
24: FUN(X[[i]], ...)
23: lapply(options, shouldEval)
22: FUN(X[[i]], ...)
21: lapply(options, shouldEval)
20: shouldEval(list)
19: unlist(shouldEval(list))
18: which(unlist(shouldEval(list)))
17: names(which(unlist(shouldEval(list)))) %||% list()
16: JSEvals(x)
15: createPayload(x)
14: toJSON(createPayload(x))
13: widget_data(x, id)
12: htmltools::tagList(container(htmltools::tagList(x$prepend, widget_html(name = class(x)[1], 
        package = attr(x, "package"), id = id, style = style, class = paste(class(x)[1], 
            "html-widget"), width = sizeInfo$width, height = sizeInfo$height), 
        x$append)), widget_data(x, id), if (!is.null(sizeInfo$runtime)) {
        tags$script(type = "application/htmlwidget-sizing", `data-for` = id, 
            toJSON(sizeInfo$runtime))
    })
11: toHTML(x, standalone = standalone)
10: as.tags.htmlwidget(x, standalone = TRUE)
9: htmltools::as.tags(x, standalone = TRUE)
8: isTag(ui)
7: rewriteTags(x, function(uiObj) {
       if (isTag(uiObj) || isTagList(uiObj) || is.character(uiObj)) 
           return(uiObj)
       else return(tagify(as.tags(uiObj)))
   }, FALSE)
6: tagify(x)
5: renderTags(html)
4: save_html(html, file = index_html, background = background, libdir = "lib")
3: html_print(htmltools::as.tags(x, standalone = TRUE), viewer = if (view) viewerFunc)
2: print.htmlwidget(x)
1: (function (x, ...) 
   UseMethod("print"))(x)

**Comment by timelyportfolio** [comment]
@femiguez thanks for the report.  The error actually stems from the `htmlwidget` construction and not `listviewer` itself.  Perhaps we should open an issue there.  One solution though might be to control the conversion to `JSON` directly since `listviewer::jsonedit` accepts text/string `JSON` as its data source.

```
jsonedit(jsonlite::toJSON(xml2, auto_unbox=TRUE))
```

**Comment by femiguez** [comment]
Thanks for the quick reply! Do you want me to post this on https://github.com/ramnathv/htmlwidgets then?

**Comment by timelyportfolio** [comment]
@femiguez yes I think that this issue would be better there.  I believe the line causing the error is here https://github.com/ramnathv/htmlwidgets/blob/29ca4f7a81a34d934e2158294b7084192be763ce/R/utils.R#L148.

```
list <- list(1, x=2)
evals <- names(which(unlist(htmlwidgets:::shouldEval(list))))
```

**Comment by timelyportfolio** [comment]
feel free to reopen - thanks!
