### ISSUE TITLE
Can't deploy listviewer to Shinyapps.io - no package called htmlwidgets ?

### ISSUE THREAD

**Issue by MarkEdmondson1234** [timelyportfolio/listviewer#8]
Hi there, I'd love for this to be in a Shiny app I have that works locally, but when I try to deploy to shinyapps.io I get the following messages:

```
* installing to library ‘/usr/local/lib/R/site-library’
* installing *source* package ‘listviewer’ ...
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘htmlwidgets’
ERROR: lazy loading failed for package ‘listviewer’
* removing ‘/usr/local/lib/R/site-library/listviewer’
################################# End Task Log ################################# 
Error: Unhandled Exception: Child Task 91001588 failed: Error building image: Error building listviewer (0.1). Build exited with non-zero status: 1
Execution halted
```

Any ideas?

**Comment by timelyportfolio** [comment]
Not sure because I have no experience with Shinyapps.io, but can you install `htmlwidgets` first and then `listviewer`?  I remember similar issues with other `htmlwidgets`. I'll try to dig those up to find the resolution.

**Comment by timelyportfolio** [comment]
here is something that might be helpful https://github.com/rstudio/shinyapps/issues/114

**Comment by MarkEdmondson1234** [comment]
Thanks I tried explicitly loading htmlwidgets but no joy yet. 
I also have 2 other htmlwidgets libraries in the app that are deploying no problem (metricsgraphics and d3heatmap).  Will check out the install dependency thread.

**Comment by timelyportfolio** [comment]
Let me see if adding to DESCRIPTION might fix the problem.

**Comment by MarkEdmondson1234** [comment]
I just forked and did that, looks like its working.....just finishing up now... :D

**Comment by timelyportfolio** [comment]
are you submitting pull?  I have it up and can just implement if easier.  let me know.

**Comment by MarkEdmondson1234** [comment]
Yes I will - it just finished and it worked :+1: Thanks!

**Comment by timelyportfolio** [comment]
ok, I'll look for your pull. Thanks for the report.  I made `listviewer` generic so other JS libraries can be included. Let me know if you like any others.
